/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/article/ArticleCard.vue')['default']
    ArticleFilters: typeof import('./src/components/article/ArticleFilters.vue')['default']
    CategoryBadge: typeof import('./src/components/article/CategoryBadge.vue')['default']
    ChapterNav: typeof import('./src/components/article/ChapterNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LongArticle: typeof import('./src/components/article/LongArticle.vue')['default']
    NavBar: typeof import('./src/components/layout/nav-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortArticle: typeof import('./src/components/article/ShortArticle.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TypeBadge: typeof import('./src/components/article/TypeBadge.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
